backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: michalzadkowski/fififi
media_folder: "/src/static/img"
public_folder: "/static/img"
locale: "pl"
editor:
  preview: false
slug:
  clean_accents: true
# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Aktualności"
    label_singular: "News"
    name: "aktualnosci"
    folder: "src/aktualnosci/posts"
    create: true
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Zajawka", name: "description", widget: "string" }
      - { label: "Data publikacji", name: "date", widget: "date" }
      - { label: "Treść", name: "body", widget: "markdown" }
  - label: "Projekty"
    name: "projekty"
    label_singular: "Projekt"
    folder: "src/projekty"
    create: true
    sortable_fields: ['tags', 'leader', 'end_date']
    fields:
      - widget: select
        label: "Aktualny?"
        name: "tags"
        multiple: false
        create: false
        options: ["aktualne", "zrealizowane"]
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Numer projektu", name: "number", widget: "string", required: false }
      - { label: "Lider projektu", name: "leader", widget: "string", required: false }
      - { label: "Partnerzy", name: "partners", widget: "text", required: false }
      - { label: "Opis", name: "description", widget: "markdown", buttons: [bold, italic, link, quote, bulleted-list, numbered-list], modes: [rich_text], editor_components: [], required: false }
      - { label: "Źródło finansowania", name: "funding_source", widget: "markdown", buttons: [bold, italic, link, quote, bulleted-list, numbered-list], modes: [rich_text], editor_components: [], required: false }
      - { label: "Data rozpoczęcia", name: "start_date", widget: "date", required: false }
      - { label: "Data zakończenia", name: "end_date", widget: "date", required: false }
      - { label: "Cel projektu", name: "goal", widget: "markdown", buttons: [bold, italic, link, quote, bulleted-list, numbered-list], modes: [rich_text], editor_components: [], required: false }
      - { label: "Grupa docelowa", name: "target_group", widget: "markdown", buttons: [bold, italic, link, quote, bulleted-list, numbered-list], modes: [rich_text], editor_components: [], required: false }
      - { label: "Formy wsparcia", name: "forms_of_support", widget: "markdown", buttons: [bold, italic, link, quote, bulleted-list, numbered-list], modes: [rich_text], editor_components: [], required: false }
      - { label: "Wartość projektu", name: "project_value", widget: "string", required: false }
      - { label: "Wartość dofinansowania", name: "funding_value", widget: "string", required: false }
      - label: "Logotypy partnerów"
        name: "partner_logos"
        required: false
        widget: "list"
        summary: '{{fields.logo}}'
        fields:
          - label: Logo
            name: logo
            widget: image
            choose_url: false
            media_folder: "/src/static/logos"
            public_folder: "/static/logos"
      - label: "Dokumenty"
        name: "documents"
        required: false
        widget: "list"
        summary: '{{fields.document}}'
        fields: 
          - label: "Dokument"
            name: "url"
            widget: file
            choose_url: false
            media_folder: "/src/static/files"
            public_folder: "/static/files" 
            media_library:
              config:
                multiple: true
          - label: "Nazwa dokumentu"
            name: "name"
            widget: "string"

  - label: "Strony"
    name: "pages"
    files:
      - label: "Statut"
        name: "statut"
        file: "src/pages/statut.md"
        fields:
          - { label: Tytuł, name: title, widget: string}
          - { label: "Treść", name: "body", widget: "markdown", modes: [rich_text], editor_components: [] }        
      - label: "O nas"
        name: "o-nas"
        file: "src/pages/o-nas.md"
        fields:
          - {label: Tytuł, name: title, widget: string}
          - { label: "Treść", name: "body", widget: "markdown", modes: [rich_text], editor_components: [] }        
      - label: "Dane urzędowe"
        name: "dane-urzedowe"
        file: "src/pages/dane-urzedowe.md"
        fields:
          - {label: Tytuł, name: title, widget: string}
          - { label: "Treść", name: "body", widget: "markdown", modes: [raw], editor_components: [] }        
      - label: "Dziękujemy"
        name: "dziekujemy"
        file: "src/pages/dziekujemy.md"
        fields:
          - {label: Tytuł, name: title, widget: string}
          - { label: "Treść", name: "body", widget: "markdown", modes: [rich_text], editor_components: [] }        