backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: michalzadkowski/fififi
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Aktualności"
    label_singular: "Wiadomość"
    name: "aktualnosci"
    folder: "src/aktualnosci/posts"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Zajawka", name: "description", widget: "string" }
      - { label: "Data publikacji", name: "date", widget: "date" }
      - { label: "Treść", name: "body", widget: "markdown" }
  - label: "Projekty"
    name: "projekty"
    label_singular: "projekt"
    folder: "src/projekty"
    create: true
    sortable_fields: ['tags', 'leader', 'end_date']
    editor:
      preview: true
    fields:
      - widget: select
        label: "Aktualne"
        name: "tags"
        multiple: false
        create: false
        options: ["aktualne", "zrealizowane"]
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Opis", name: "description", widget: "string" }
      - { label: "Lider", name: "leader", widget: "string" }
      - { label: "Data rozpoczęcia", name: "start_date", widget: "datetime" }
      - { label: "Data zakończenia", name: "end_date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }        
  - label: "Strony"
    name: "pages"
    files:
      - label: "Statut"
        name: "statut"
        file: "src/pages/statut.md"
        fields:
          - {label: Tytuł, name: title, widget: string}
          - { label: "Treść", name: "body", widget: "markdown" }        
      - label: "O nas"
        name: "o-nas"
        file: "src/pages/o-nas.md"
        fields:
          - {label: Tytuł, name: title, widget: string}
          - { label: "Treść", name: "body", widget: "markdown" }        
      - label: "Dane urzędowe"
        name: "dane-urzedowe"
        file: "src/pages/dane-urzedowe.md"
        fields:
          - {label: Tytuł, name: title, widget: string}
          - { label: "Treść", name: "body", widget: "markdown" }        
      # - label: "Kontakt"
      #   name: "kontakt"
      #   file: "src/pages/kontakt.md"
      #   fields:
      #     - {label: Title, name: title, widget: string}
      #     - { label: "Body", name: "body", widget: "markdown" }        
      - label: "Dziękujemy"
        name: "dziekujemy"
        file: "src/pages/dziekujemy.md"
        fields:
          - {label: Tytuł, name: title, widget: string}
          - { label: "Treść", name: "body", widget: "markdown" }        