backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: michalzadkowski/fififi
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Aktualności"
    label_singular: "Wiadomość"
    name: "aktualnosci"
    folder: "src/aktualnosci/posts"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Zajawka", name: "description", widget: "string" }
      - { label: "Data publikacji", name: "date", widget: "date" }
      - { label: "Treść", name: "body", widget: "markdown" }
  - label: "Projekty"
    name: "projekty"
    label_singular: "projekt"
    folder: "src/projekty"
    create: true
    sortable_fields: ['tags', 'leader', 'end_date']
    editor:
      preview: true
    fields:
      - widget: select
        label: "Aktualny?"
        name: "tags"
        multiple: false
        create: false
        options: ["aktualne", "zrealizowane"]
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Numer projektu", name: "number", widget: "string" }
      - { label: "Lider projektu", name: "leader", widget: "string" }
      - { label: "Partnerzy", name: "partners", widget: "text" }
      - { label: "Opis", name: "description", widget: "markdown", buttons: [bold, italic, link, quote, bulleted-list, numbered-list], modes: [rich_text], editor_components: [] }
      - { label: "Źródło finansowania", name: "funding_source", widget: "markdown", buttons: [bold, italic, link, quote, bulleted-list, numbered-list], modes: [rich_text], editor_components: [] }
      - { label: "Data rozpoczęcia", name: "start_date", widget: "date", format: "DD-MM-YYYY" }
      - { label: "Data zakończenia", name: "end_date", widget: "date", format: "DD-MM-YYYY" }
      - { label: "Cel projektu", name: "goal", widget: "markdown", buttons: [bold, italic, link, quote, bulleted-list, numbered-list], modes: [rich_text], editor_components: [] }
      - { label: "Grupa docelowa", name: "target_group", widget: "markdown", buttons: [bold, italic, link, quote, bulleted-list, numbered-list], modes: [rich_text], editor_components: [] }
      - { label: "Formy wsparcia", name: "forms_of_support", widget: "markdown", buttons: [bold, italic, link, quote, bulleted-list, numbered-list], modes: [rich_text], editor_components: [] }
      - { label: "Wartość projektu", name: "project_value", widget: "string" }
      - { label: "Wartość dofinansowania", name: "funding_value", widget: "string" }
      - label: "Logotypy partnerów"
        name: "partner_logos"
        widget: "list"
        summary: '{{fields.logo}}'
        field: {label: Logo, name: logo, widget: image, choose_url: false}
      - label: "Dokumenty"
        name: "documents"
        widget: "list"
        summary: '{{fields.document}}'
        field: 
          label: "Dokument"
          name: "document"
          widget: file
          choose_url: false
          media_folder: "/static/files"
          media_library:
            config:
              multiple: true

  - label: "Strony"
    name: "pages"
    files:
      - label: "Statut"
        name: "statut"
        file: "src/pages/statut.md"
        fields:
          - { label: Tytuł, name: title, widget: string}
          - { label: "Treść", name: "body", widget: "markdown" }        
      - label: "O nas"
        name: "o-nas"
        file: "src/pages/o-nas.md"
        fields:
          - {label: Tytuł, name: title, widget: string}
          - { label: "Treść", name: "body", widget: "markdown" }        
      - label: "Dane urzędowe"
        name: "dane-urzedowe"
        file: "src/pages/dane-urzedowe.md"
        fields:
          - {label: Tytuł, name: title, widget: string}
          - { label: "Treść", name: "body", widget: "markdown" }        
      # - label: "Kontakt"
      #   name: "kontakt"
      #   file: "src/pages/kontakt.md"
      #   fields:
      #     - {label: Title, name: title, widget: string}
      #     - { label: "Body", name: "body", widget: "markdown" }        
      - label: "Dziękujemy"
        name: "dziekujemy"
        file: "src/pages/dziekujemy.md"
        fields:
          - {label: Tytuł, name: title, widget: string}
          - { label: "Treść", name: "body", widget: "markdown" }        